# Change these first
owner: constructions-incongrues # Your GitHub organization or username, where this repository lives
repo: status-pastis # The name of this repository

sites:
  - name: Home
    url: https://www.pastis-hosting.net
  - name: Panel
    url: https://panel.pastis-hosting.net
  - name: Yuno
    url: https://yuno.pastis-hosting.net
    
assignees:
  - trivoallan

status-website:
  cname: www.pastis-hosting.net
  name: Pastis Hosting
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: dark
  navbar:
    - title: Github
      href: https://github.com/constructions-incongrues/status-pastis/
    - title: Constructions
      href: https://status.constructions-incongrues.net
    - title: Interzone
      href: https://status.interzone.network
    - title: Jean-Cloude
      href: https://status.jeancloude.club
    - title: Pantagruweb
      href: https://status.pantagruweb.club
    - title: Pastis
      href: https://pastis-hosting.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
