# Change these first
owner: constructions-incongrues # Your GitHub organization or username, where this repository lives
repo: status-pastis # The name of this repository

sites:
  - name: Homepage
    url: https://www.pastis-hosting.net
  - name: Panel
    url: https://panel.pastis-hosting.net

assignees:
  - trivoallan

status-website:
  cname: www.pastis-hosting.net
  name: Pastis Hosting
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: dark
  navbar:
    - title: Constructions Incongrues
      href: https://status.constructions-incongrues.net
    - title: Interzone Network
      href: https://status.interzone.network

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
